trigger:
 branches:
   include:
     - main

resources:
 repositories:
   - repository: self
     type: github
     endpoint: gopalepic
     name: gopalepic/event-driven-pipeline

stages:
  - stage: BuildAndDeployFunction
    jobs:
      - job: BuildFunction
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'
          - script: |
              npm install
              npm run build 
            workingDirectory: 'process_data'
            displayName: 'Build Fucntion App'
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: 'process_data'
              includeRootFolder: false
              archiveType: zip
              archiveFile: '$(Build.ArtifactStagingDirectory)/function-app.zip'
              replaceExistingArchive: true
            displayName: 'Archive Function App'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'function-app'
              publishLocation: Container
            displayName: 'Publish Function App Artifact'
        
      - job: DeployFuncion
        dependsOn: BuildFunction
        pool:
         vmImage: 'ubuntu-latest'
        steps:
          - task: AzureFunctionApp@2
            inputs:
             azureSubscription:''
             appType: 'functionApp'


          