name: Deploy Azure Functions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        cd process_data
        npm install
        
    - name: Build Function App
      run: |
        cd process_data
        npm run build
        
    - name: Zip Function App
      run: |
        cd process_data
        zip -r ../function-app.zip . -x "*.git*" "node_modules/.cache/*"
        
    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: 'process-data-dxjhc2i0'
        package: './function-app.zip'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
